/* CREATION DE LA TABLE ARTICLES */

CREATE TABLE node_articles
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, title VARCHAR(100), content VARCHAR(256), author INT, created_at DATETIME);

/* CREATION DE LA TABLE COMMENTS */

CREATE TABLE node_comments
(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, article_id INT, author INT, content VARCHAR(256), created_at DATETIME);